[project]
template = "template-tokens-uno-astro"
title = "Aledi"
name = "aledi"
description = "Ilustradora y diseñadora gráfica"
directory = "/home/ortiz/Dev/aledi"

[project.author]
name = "Antonio Ortiz"
username = "ortiz-antonio"
url = "https://ortiz.studio"

[project.links]
repository = "git@github.com:ortiz-antonio/aledi.git"
homepage = "https://ortiz-antonio.github.io/aledi"
